### ISSUE TITLE
Tides grant final report

### ISSUE THREAD

**Issue by janetpkr** [creativecommons/school-of-open#4]

**Comment by janetpkr** [comment]
Need to get SOO kenya CC0 materials for report. 

Need initial draft by mid-April

**Comment by Scott-CC** [comment]
Make sure to get everyone to turn in their expenses.  I know based on our previous discussions some may drift beyond April, but it never hurts to remind them.

**Comment by janetpkr** [comment]
Yes, once activities are run, leads will turn in expenses to get reimbursed. That's a ways off.
